START "Aspen Import" CMD.exe /c "C:\Dropbox\EpicorImplementation\1-ASPN\_DMT_ASPN_Test_Load.bat"
REM START "Versalift China" CMD.exe /c "C:\Dropbox\EpicorImplementation\2-VCN\_DMT_VCN_Test_Load.bat"
REM START "Versalift Forestry" CMD.exe /c "C:\Dropbox\EpicorImplementation\3-VF\_DMT_VF_Test_Load.bat"
START "Versalift Midwest" CMD.exe /c "C:\Dropbox\EpicorImplementation\4-VMW\_DMT_VMW_Test_Load.bat"
START "Versalift Denmark" CMD.exe /c "C:\Dropbox\VDK\_DMT_VDK_Test_Load.bat"
START "Versalift France" CMD.exe /c "C:\Dropbox\VFR\_DMT_VFR_Test_Load.bat"