MkDir "1-Test-Load"
MkDir "2.2-Review_With_Team"
MkDir "2.5-Needs_Review"
MkDir "2-Test-Errors"
MkDir "3-Test-Done"
MkDir "4-GL_Related"
MkDir "5-Prod-Load"
MkDir "6-Prod-Done"
MkDir "9-Sample DMT Templates"
