START "Aspen Import" CMD.exe /c 			""C:\Users\PaulM\OneDrive - TIME MANUFACTURING COMPANY\EpicorImplementation\Z_Scripts\__ASPN_Test_Load.bat""
REM START "Versalift China" CMD.exe /c 		""C:\Users\PaulM\OneDrive - TIME MANUFACTURING COMPANY\EpicorImplementation\Z_Scripts\__VCN_Test_Load.bat""
REM START "Versalift Forestry" CMD.exe /c 	""C:\Users\PaulM\OneDrive - TIME MANUFACTURING COMPANY\EpicorImplementation\Z_Scripts\__VF_Test_Load.bat""
REM START "Versalift Midwest" CMD.exe /c 	""C:\Users\PaulM\OneDrive - TIME MANUFACTURING COMPANY\EpicorImplementation\Z_Scripts\__VMW_Test_Load.bat""
START "Versalift Denmark" CMD.exe /c 		""C:\Users\PaulM\OneDrive - TIME MANUFACTURING COMPANY\EpicorImplementation\Z_Scripts\__VDK_Test_Load.bat""
START "Versalift France" CMD.exe /c 		""C:\Users\PaulM\OneDrive - TIME MANUFACTURING COMPANY\EpicorImplementation\Z_Scripts\__VFR_Test_Load.bat""